//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficPolice
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrafficPoliceEntities : DbContext
    {
        public TrafficPoliceEntities()
            : base("name=TrafficPoliceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<Inspection_History> Inspection_History { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tech_inspect_car> Tech_inspect_car { get; set; }
        public virtual DbSet<Technical_Passport> Technical_Passport { get; set; }
        public virtual DbSet<Traffic_Police_Officer> Traffic_Police_Officer { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
