//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficPolice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tech_inspect_car
    {
        public int ID_inspect { get; set; }
        public Nullable<int> ID_Car { get; set; }
        public Nullable<int> ID_Owner { get; set; }
        public Nullable<int> ID_History { get; set; }
        public Nullable<int> ID_Officer { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Inspection_History Inspection_History { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual Traffic_Police_Officer Traffic_Police_Officer { get; set; }
    }
}
